/**
 * Contextual reference bank for Bhenchod Bartender.
 * Each entry: title, franchise, triggers, moment/character beat (not bare name-drops).
 * franchise id used for anti-repetition (no same franchise within last 5 lines).
 */

/** @typedef {'show'|'movie'} RefType */
/** @typedef {string} BartenderTrigger */

/**
 * @typedef {object} BartenderReference
 * @property {string} id
 * @property {string} title
 * @property {string} franchise
 * @property {RefType} type
 * @property {'nandini'|'kunal'|'any'} playerAffinity
 * @property {BartenderTrigger[]} triggers
 * @property {string} famousMoment
 * @property {string} quoteEnergy
 * @property {string} tone
 * @property {Partial<Record<BartenderTrigger, string>>} usageExamples
 * @property {string} [iconicLine] — famous quote to weave into roast (overrides franchise bank)
 */

/** @type {BartenderTrigger[]} */
export const BARTENDER_TRIGGERS = [
  'lucky',
  'gfy',
  'bluff_landed',
  'bluff_win',
  'bullshit_correct',
  'bullshit_wrong',
  'bullshit',
  'close_call',
  'heat',
  'chaos',
  'steal',
  'comeback',
  'book',
  'game_over',
  'roast',
  'question',
  'dare',
  'slow_turn',
  'drink',
  'drink_assign',
];

/** Franchises the bartender should use most often (canon media). */
export const PRIMARY_BARTENDER_FRANCHISES = new Set([
  'brooklyn-nine-nine',
  'spartacus',
  'dhurandhar-p1',
  'dhurandhar-p2',
  'paatal-lok',
  'night-manager',
  'kuch-kuch-hota-hai',
  'agent-sai',
  'hardcore-henry',
  'ip-man',
  'sanju',
  'ferris-bueller',
  'gully-boy',
  'scary-movie',
  'naked-gun',
  'undisputed',
]);

/**
 * Core canon references — both players, most triggers.
 * Iconic Bollywood = KKHH-style dialogue energy (inspired, not long verbatim quotes).
 */
export const PRIMARY_REFERENCES = [
  {
    id: 'core-b99-holt-gfy',
    title: 'Brooklyn Nine-Nine',
    franchise: 'brooklyn-nine-nine',
    type: 'show',
    playerAffinity: 'any',
    triggers: ['gfy', 'close_call', 'bullshit_wrong'],
    famousMoment: 'Captain Holt deadpan after Jake\'s overconfidence implodes',
    quoteEnergy: 'Cool cool cool — then instant Holt silence',
    tone: 'comedic deflate',
    usageExamples: {
      gfy: '{name} bhai, cool cool cool cool — full Jake energy, then Go Fuck Yourself, pond miss. Holt would just stare and sip water.',
      close_call: '{name}, teen card — Jake Peralta confidence, Holt disappointment. Pond said Go Fuck Yourself.',
      bullshit_wrong: 'Wrong bullshit call, {name} — Boyle-level passion, Holt-level consequences.',
    },
  },
  {
    id: 'core-b99-jake-bluff',
    title: 'Brooklyn Nine-Nine',
    franchise: 'brooklyn-nine-nine',
    type: 'show',
    playerAffinity: 'any',
    triggers: ['bluff_landed', 'bluff_win', 'bullshit_correct'],
    famousMoment: 'Jake celebrates too early — case still open',
    quoteEnergy: 'Victory dance before the reveal',
    tone: 'premature triumph',
    usageExamples: {
      bluff_landed: '{name} bluffed with full Jake Peralta victory dance — partner believed Go Fuck Yourself. Case still open, ego closed.',
      bullshit_correct: 'Bullshit call landed, {name} — detective work with Jake swagger, liar caught holding cards.',
    },
  },
  {
    id: 'core-b99-terry-heat',
    title: 'Brooklyn Nine-Nine',
    franchise: 'brooklyn-nine-nine',
    type: 'show',
    playerAffinity: 'any',
    triggers: ['heat', 'slow_turn', 'chaos'],
    famousMoment: 'Terry Crews energy — table needs action NOW',
    quoteEnergy: 'Yogurt-level intensity on a dead case',
    tone: 'urgent comedy',
    usageExamples: {
      heat: 'Precinct deadlier than this table, {name} — sirf Go Fuck Yourself echo. Terry would bench-press the pond.',
      slow_turn: '{name}, turn freeze — Nine-Nine paperwork moves faster. Card maango ya Go Fuck Yourself.',
      chaos: 'Chaos button = precinct when the vending machine breaks. Same panic, worse cards.',
    },
  },
  {
    id: 'core-spartacus-gfy',
    title: 'Spartacus',
    franchise: 'spartacus',
    type: 'show',
    playerAffinity: 'any',
    triggers: ['gfy', 'close_call', 'game_over'],
    famousMoment: 'Blood and sand — fight impossible odds anyway',
    quoteEnergy: 'I am Spartacus stubbornness',
    tone: 'epic struggle',
    usageExamples: {
      gfy: '{name}, Go Fuck Yourself + pond miss — Rome had better odds than your hand tonight.',
      close_call: 'Teen card, one short — Spartacus arena energy, pond still said no.',
      game_over: 'Credits roll — {name} survived the arena. Blood, sand, and Go Fuck Yourself.',
    },
  },
  {
    id: 'core-spartacus-bluff',
    title: 'Spartacus',
    franchise: 'spartacus',
    type: 'show',
    playerAffinity: 'any',
    triggers: ['bluff_landed', 'bullshit_correct', 'book'],
    famousMoment: 'Gladiator deception — strike when they think you\'re finished',
    quoteEnergy: 'Arena politics and hidden blade',
    tone: 'brutal cunning',
    usageExamples: {
      bluff_landed: '{name} bluffed like a gladiator playing dead — Go Fuck Yourself face, cards hidden. Partner walked into the trap.',
      bullshit_correct: 'Bullshit expose — {name} pulled the hidden blade. Liar drew blood (four cards).',
      book: 'Four cards = set complete. {name} owns the arena now.',
    },
  },
  {
    id: 'core-dhurandhar-p1-book',
    title: 'Dhurandhar Part 1',
    franchise: 'dhurandhar-p1',
    type: 'show',
    playerAffinity: 'any',
    triggers: ['book', 'game_over', 'roast'],
    famousMoment: 'Part 1 mastermind — operation written before anyone blinked',
    quoteEnergy: 'Ranveer-scale dom swagger, season one audacity',
    tone: 'unhinged alpha',
    usageExamples: {
      book: '{name} ne set complete kiya — Dhurandhar Part 1 planning thi, table pe script already locked.',
      game_over: '{name} jeet gaya — Part 1 finale energy. Absolute fucking cinema.',
      roast: '{name}, questionnaire reads like Dhurandhar Part 1 confession — dom energy, filthy paperwork.',
    },
  },
  {
    id: 'core-dhurandhar-p2-gfy',
    title: 'Dhurandhar Part 2',
    franchise: 'dhurandhar-p2',
    type: 'show',
    playerAffinity: 'any',
    triggers: ['gfy', 'chaos', 'lucky'],
    famousMoment: 'Part 2 escalation — stakes doubled, ego still louder',
    quoteEnergy: 'Sequel chaos — same dom, bigger explosion',
    tone: 'sequel intensity',
    usageExamples: {
      gfy: '{name} walked in like Dhurandhar Part 2 climax — Go Fuck Yourself mila, pond miss. Sequel pain.',
      chaos: 'Part 2 rules — {name}, bartender injected chaos like a mid-season twist. Table on fire.',
      lucky: 'Go Fuck Yourself ke baad pond sympathy — Part 2 plot armor. Undeserved, cinematic.',
    },
  },
  {
    id: 'core-paatal-heat',
    title: 'Paatal Lok',
    franchise: 'paatal-lok',
    type: 'show',
    playerAffinity: 'any',
    triggers: ['heat', 'slow_turn', 'bullshit_correct'],
    famousMoment: 'Hathiram slow grind — case open, patience brutal',
    quoteEnergy: 'Paatal interrogation — no quick answers',
    tone: 'noir patience',
    usageExamples: {
      heat: 'Paatal Lok interrogation has more card transfers than this table, {name}. Go Fuck Yourself loop.',
      slow_turn: '{name} hogging the turn — Hathiram would still be asking the same question.',
      bullshit_correct: 'Bullshit call — {name} caught the liar like Hathiram catching a false alibi. Four cards, case file updated.',
    },
  },
  {
    id: 'core-paatal-gfy',
    title: 'Paatal Lok',
    franchise: 'paatal-lok',
    type: 'show',
    playerAffinity: 'any',
    triggers: ['gfy', 'close_call', 'chaos'],
    famousMoment: 'Swagat hai Paatal Lok mein — underworld meets bureaucracy',
    quoteEnergy: 'System corrupt, table worse',
    tone: 'dark bureaucracy',
    usageExamples: {
      gfy: 'Swagat hai Paatal Lok mein, {name} — Go Fuck Yourself, pond miss. Underworld paperwork.',
      close_call: 'Teen card — case almost cracked, pond ne file reject. Paatal Lok emotional damage.',
      chaos: 'Chaos event — upar normal, andar system chud gaya. Go Fuck Yourself.',
    },
  },
  {
    id: 'core-nightmanager-bluff',
    title: 'The Night Manager',
    franchise: 'night-manager',
    type: 'show',
    playerAffinity: 'any',
    triggers: ['bluff_landed', 'bluff_win', 'steal'],
    famousMoment: 'Jonathan Pine quiet op — lie clean, partner never sees it',
    quoteEnergy: 'Handler chess — background scam',
    tone: 'cool control',
    usageExamples: {
      bluff_landed: 'Night Manager op — {name} lied quiet, partner folded on Go Fuck Yourself. Handler never flinched.',
      steal: 'Background snatch — {name} took a card like a Pine side operation. Daylight invisible.',
    },
  },
  {
    id: 'core-nightmanager-heat',
    title: 'The Night Manager',
    franchise: 'night-manager',
    type: 'show',
    playerAffinity: 'any',
    triggers: ['heat', 'slow_turn', 'game_over'],
    famousMoment: 'Long undercover wait — table frozen, op still running',
    quoteEnergy: 'Luxury hotel, slow-burn tension',
    tone: 'spy patience',
    usageExamples: {
      heat: 'Night Manager slow op — {name}, table frozen longer than a Cairo stakeout.',
      slow_turn: '{name} taking forever — even Jonathan Pine would have played a card by now.',
      game_over: 'Op complete — {name} won like a Night Manager finale. Quiet dom, loud result.',
    },
  },
  {
    id: 'core-kkhh-friendship-gfy',
    title: 'Kuch Kuch Hota Hai',
    franchise: 'kuch-kuch-hota-hai',
    type: 'movie',
    playerAffinity: 'any',
    triggers: ['gfy', 'lucky', 'roast'],
    famousMoment: 'Pyar dosti hai — friendship speech before heartbreak lands',
    quoteEnergy: 'Iconic KKHH basketball-court honesty',
    tone: 'bollywood romance wreck',
    usageExamples: {
      gfy: '{name} bhai, kuch kuch hota hai — partner ne Go Fuck Yourself bola, pond miss. Dosti thi, result nahi.',
      lucky: 'Go Fuck Yourself ke baad pond match — KKHH third-act twist. Rahul would still miss the timing.',
      roast: '{name}, filth file reads like KKHH diary — pyar, dosti, aur pond ne sabko Go Fuck Yourself.',
    },
  },
  {
    id: 'core-kkhh-basketball-close',
    title: 'Kuch Kuch Hota Hai',
    franchise: 'kuch-kuch-hota-hai',
    type: 'movie',
    playerAffinity: 'any',
    triggers: ['close_call', 'book', 'drink'],
    famousMoment: 'Basketball friendship — one shot away from the win',
    quoteEnergy: 'Tujhe yaad hai woh din — iconic KKHH nostalgia punch',
    tone: 'nostalgic gut-punch',
    usageExamples: {
      close_call: 'Teen card — KKHH basketball energy, {name}. Ek shot chahiye tha, pond ne Go Fuck Yourself.',
      book: 'Set complete — {name} ne four cards jod diye. KKHH happy ending, bar tab still due.',
      drink: 'Drink assign — KKHH college farewell energy. {name}, shot time. Kuch kuch hota hai, mostly regret.',
    },
  },
  {
    id: 'core-kkhh-bullshit',
    title: 'Kuch Kuch Hota Hai',
    franchise: 'kuch-kuch-hota-hai',
    type: 'movie',
    playerAffinity: 'any',
    triggers: ['bullshit_correct', 'bullshit_wrong', 'bluff_landed'],
    famousMoment: 'Love triangle reveal — someone was lying about their hand all along',
    quoteEnergy: 'Dil toh pagal hai — truth finally drops',
    tone: 'melodrama expose',
    usageExamples: {
      bullshit_correct: 'Bullshit call — {name} exposed the lie. KKHH triangle energy: cards were with them the whole time.',
      bullshit_wrong: 'Wrong bullshit, {name} — KKHH misunderstanding montage. You accused, they were clean.',
      bluff_landed: 'Bluff landed — {name} said Go Fuck Yourself with SRK smile. Partner believed. Iconic scam.',
    },
  },
  {
    id: 'core-agent-sai-gfy',
    title: 'Agent Sai Srinivasa Athreya',
    franchise: 'agent-sai',
    type: 'movie',
    playerAffinity: 'any',
    triggers: ['gfy', 'bullshit_wrong', 'heat'],
    famousMoment: 'Amateur detective — wrong suspect, wrong evidence, full confidence',
    quoteEnergy: 'Investigation montage, embarrassing conclusion',
    tone: 'detective comedy',
    usageExamples: {
      gfy: '{name} spent five turns investigating that hand like Agent Sai. Wrong suspect. Wrong evidence. Go Fuck Yourself.',
      bullshit_wrong: 'Agent Sai wrong case file — your bullshit call, {name}. Detective cosplay, penalty served.',
      heat: 'Case colder than this table, {name}. Hathiram would transfer a card faster.',
    },
  },
  {
    id: 'core-hardcore-chaos',
    title: 'Hardcore Henry',
    franchise: 'hardcore-henry',
    type: 'movie',
    playerAffinity: 'any',
    triggers: ['chaos', 'lucky', 'game_over'],
    famousMoment: 'First-person chaos — nonstop POV violence, no pause',
    quoteEnergy: 'Adrenaline overdose in one continuous shot',
    tone: 'chaotic action',
    usageExamples: {
      chaos: 'Hardcore Henry POV — {name}, bartender injected chaos into Go Fish. Nonstop, no cut.',
      lucky: 'Go Fuck Yourself then pond luck — Henry grabbing a weapon mid-sprint, {name}. Messy survival.',
      game_over: 'Credits roll — {name} survived Hardcore Henry runtime. Absolute violence, absolute cinema.',
    },
  },
  {
    id: 'core-ipman-book',
    title: 'Ip Man',
    franchise: 'ip-man',
    type: 'movie',
    playerAffinity: 'any',
    triggers: ['book', 'bluff_landed', 'bullshit_correct'],
    famousMoment: 'Wing Chun — four hits before you blink, calm master',
    quoteEnergy: 'Economic precision, devastating efficiency',
    tone: 'martial precision',
    usageExamples: {
      book: 'Ip Man finishing combo — {name} set complete, four cards, economic violence.',
      bluff_landed: '{name} bluffed with Ip Man calm — Go Fuck Yourself face, hidden cards. Partner never saw the strike.',
      bullshit_correct: 'Bullshit call — {name} exposed the lie in four clean hits. Wing Chun truth.',
    },
  },
  {
    id: 'core-sanju-lucky',
    title: 'Sanju',
    franchise: 'sanju',
    type: 'movie',
    playerAffinity: 'any',
    triggers: ['lucky', 'gfy', 'roast'],
    famousMoment: 'Bad decisions montage — still survives anyway',
    quoteEnergy: 'Mistake after mistake, biopic sympathy anyway',
    tone: 'absurd survival',
    usageExamples: {
      lucky: 'Go Fuck Yourself mila, pond ne card diya — {name}, ye Sanju comeback montage hai, card game nahi.',
      gfy: 'Sanju weekend energy, {name} — galat decision, Go Fuck Yourself, phir bhi ego alive.',
      roast: '{name}, questionnaire reads like Sanju confession tape — bad choices, iconic survival.',
    },
  },
  {
    id: 'core-ferris-lucky',
    title: "Ferris Bueller's Day Off",
    franchise: 'ferris-bueller',
    type: 'movie',
    playerAffinity: 'any',
    triggers: ['lucky', 'bluff_landed', 'slow_turn'],
    famousMoment: 'Zero consequences — skips school, wins anyway',
    quoteEnergy: 'Life moves pretty fast — vibes only',
    tone: 'carefree scam',
    usageExamples: {
      lucky: 'Zero consequences, {name} — Ferris Bueller proud of that pond luck after Go Fuck Yourself.',
      bluff_landed: 'Ferris energy bluff — {name} lied, partner believed, no homework, full scam.',
      slow_turn: '{name} hogging the turn — Ferris would have asked, GFY\'d, and stolen a car by now.',
    },
  },
  {
    id: 'core-gullyboy-book',
    title: 'Gully Boy',
    franchise: 'gully-boy',
    type: 'movie',
    playerAffinity: 'any',
    triggers: ['book', 'lucky', 'game_over'],
    famousMoment: 'Apna time aayega — underdog turns the room',
    quoteEnergy: 'Rap battle turnaround, street poetry win',
    tone: 'underdog triumph',
    usageExamples: {
      book: 'Set complete — {name}, apna time aayega energy. Mic drop on four cards.',
      lucky: 'Go Fuck Yourself ke baad pond match — Gully Boy third act, {name}. Underground win.',
      game_over: '{name} won — Gully Boy finale. Street poetry, dom table sealed.',
    },
  },
  {
    id: 'core-scary-chaos',
    title: 'Scary Movie',
    franchise: 'scary-movie',
    type: 'movie',
    playerAffinity: 'any',
    triggers: ['chaos', 'bluff_landed', 'bullshit_wrong'],
    famousMoment: 'Parody chaos — rules stopped making sense ages ago',
    quoteEnergy: 'Genre parody pile-up, zero logic',
    tone: 'absurd spoof',
    usageExamples: {
      chaos: 'Scary Movie rules, {name} — match stopped making sense six turns ago. Bartender agrees.',
      bluff_landed: 'Bluff so stupid it\'s Scary Movie logic — {name}, partner still believed Go Fuck Yourself.',
      bullshit_wrong: 'Wrong bullshit, {name} — Scary Movie detective. Case file is a joke.',
    },
  },
  {
    id: 'core-nakedgun-bullshit',
    title: 'Naked Gun',
    franchise: 'naked-gun',
    type: 'movie',
    playerAffinity: 'any',
    triggers: ['bullshit_correct', 'chaos', 'heat'],
    famousMoment: 'Leslie Nielsen deadpan — serious face, nonsense events',
    quoteEnergy: 'Police procedural parody, grave tone',
    tone: 'absurd procedural',
    usageExamples: {
      bullshit_correct: 'Naked Gun investigation — {name} bullshit call exposed the liar. Case closed, four cards.',
      chaos: 'Naked Gun territory, {name} — serious faces, nonsense table. Bartender filing a false report.',
      heat: 'Surely you can transfer a card, {name}. Table: no. Naked Gun absurdity.',
    },
  },
  {
    id: 'core-undisputed2-book',
    title: 'Undisputed 2',
    franchise: 'undisputed',
    type: 'movie',
    playerAffinity: 'any',
    triggers: ['book', 'gfy', 'bluff_landed'],
    famousMoment: 'Prison yard fight — respect taken by force',
    quoteEnergy: 'Boyka underground combat, brutal efficiency',
    tone: 'brutal sports',
    usageExamples: {
      book: 'Undisputed 2 KO — {name} set complete. Opponent still on the mat.',
      gfy: 'Go Fuck Yourself + pond miss — {name} ate a yard shot. Undisputed pain.',
      bluff_landed: '{name} bluffed like a prison-yard feint — Go Fuck Yourself, cards hidden. Respect stolen.',
    },
  },
  {
    id: 'core-undisputed3-gameover',
    title: 'Undisputed 3',
    franchise: 'undisputed',
    type: 'movie',
    playerAffinity: 'any',
    triggers: ['game_over', 'bullshit_correct', 'drink'],
    famousMoment: 'Tournament bracket — last man standing takes all',
    iconicLine: 'I am the most complete fighter in the world.',
    quoteEnergy: 'Final round brutality',
    tone: 'tournament climax',
    usageExamples: {
      game_over: '{name} won — Undisputed 3 bracket cleared. Last fighter standing.',
      bullshit_correct: 'Bullshit call — {name} knocked the lie out cold. Undisputed 3 expose.',
      drink: 'Drink assign — {name} lost the round, bar tab is the penalty. Undisputed rules.',
    },
  },
];

/** Nandini's watchlist — bartender should feel like he knows her taste. */
export const NANDINI_REFERENCES = [
  {
    id: 'nandini-b99-jake-bluff',
    title: 'Brooklyn Nine-Nine',
    franchise: 'brooklyn-nine-nine',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['bluff_landed', 'bluff_win', 'gfy', 'bullshit_wrong'],
    famousMoment: 'Jake Peralta overconfidence → Captain Holt deadpan disappointment',
    quoteEnergy: 'Cool cool cool cool cool — then instant regret',
    tone: 'comedic deflate',
    usageExamples: {
      bluff_landed: '{name}, you walked into that bluff with full Jake Peralta confidence. Five seconds later? Captain Holt face. Absolute fucking disaster.',
      gfy: '{name} bhai, cool cool cool cool — asked for the card, got Go Fuck Yourself, pond miss. Holt would just stare and sip water.',
      bullshit_wrong: '{name}, wrong bullshit call with Boyle-level investment. Holt energy on the table: silent judgment.',
    },
  },
  {
    id: 'nandini-b99-boyle-heat',
    title: 'Brooklyn Nine-Nine',
    franchise: 'brooklyn-nine-nine',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['heat', 'chaos'],
    famousMoment: 'Boyle way too invested in a minor situation',
    quoteEnergy: 'Overcommitted side character energy',
    tone: 'chaotic earnest',
    usageExamples: {
      heat: 'Table pe sirf Go Fuck Yourself echo ho raha hai, {name}. Boyle bhi itna invested nahi hota kisi dead case mein.',
      chaos: '{name}, chaos button = Nine-Nine precinct when paperwork catches fire. Same panic, worse cards.',
    },
  },
  {
    id: 'nandini-modfam-phil-gfy',
    title: 'Modern Family',
    franchise: 'modern-family',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['gfy', 'close_call', 'lucky'],
    famousMoment: 'Phil Dunphy optimism — everything will work out',
    quoteEnergy: 'Innocent confidence before reality hits',
    tone: 'warm then wrecked',
    usageExamples: {
      gfy: 'That ask had Phil Dunphy energy, {name}. Thought everything would work out. Then the table told you Go Fuck Yourself.',
      close_call: '{name}, teen card — Phil planning the surprise party, pond ne Go Fuck Yourself. Gloria would just yell.',
      lucky: 'Phil Dunphy luck — {name} got Go Fuck Yourself then pond sympathy. Modern Family B-plot rescue.',
    },
  },
  {
    id: 'nandini-modfam-gloria-steal',
    title: 'Modern Family',
    franchise: 'modern-family',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['steal', 'book', 'chaos'],
    famousMoment: 'Gloria chaos — loud, decisive, zero apology',
    quoteEnergy: 'Sudden domestic storm',
    tone: 'chaotic matriarch',
    usageExamples: {
      steal: '{name} ne card chura liya — Gloria entering a room energy. No warning, full volume, Kunal still owns the couch.',
      book: 'Set complete, {name} — Gloria celebration, Cam would cry, table still Kunal\'s dom hour.',
    },
  },
  {
    id: 'nandini-dhoota-warning',
    title: 'Dhoota',
    franchise: 'dhoota',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['close_call', 'gfy', 'bullshit_wrong'],
    famousMoment: 'Warnings ignored — signs everywhere, still walks into trap',
    quoteEnergy: 'Kismat messaged, you swiped away',
    tone: 'existential tease',
    usageExamples: {
      close_call: 'Warning mil gayi thi, sign mil gaya tha, {name}. Teen card, pond ne Go Fuck Yourself. Pure Dhootha energy.',
      gfy: '{name}, Dhootha twist — partner ne Go Fuck Yourself, pond miss. You had every clue, ignored all.',
    },
  },
  {
    id: 'nandini-st-denis-chaos',
    title: 'St. Denis Medical',
    franchise: 'st-denis-medical',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['chaos', 'heat'],
    famousMoment: 'Hospital chaos — competent facade, disaster behind doors',
    quoteEnergy: 'Medical sitcom panic under fluorescent lights',
    tone: 'frazzled professional',
    usageExamples: {
      chaos: 'St. Denis Medical energy, {name} — looks calm, inside pure chaos. Bartender just called code blue on this table.',
      heat: 'ER waiting room has more card transfers than this table, {name}. Go Fuck Yourself loop on repeat.',
    },
  },
  {
    id: 'nandini-gentleman-bluff',
    title: 'Gentleman',
    franchise: 'gentleman',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['bluff_landed', 'steal', 'roast'],
    famousMoment: 'Suave criminal charm — looks gentleman, moves like heist',
    quoteEnergy: 'Polite surface, dirty underneath',
    tone: 'stylish con',
    usageExamples: {
      bluff_landed: '{name} ne Go Fuck Yourself bola with Gentleman smile — cards hidden, partner folded. Suave scam.',
      steal: 'Gentleman heist — {name} slipped one card out like it was manners, not theft.',
    },
  },
  {
    id: 'nandini-masterchef-bluff',
    title: 'MasterChef India',
    franchise: 'masterchef-india',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['bluff_landed', 'bluff_win', 'bullshit_correct', 'close_call'],
    famousMoment: 'Finale plating panic — judges destroy the dish',
    quoteEnergy: 'Beautiful presentation, horrifying taste',
    tone: 'competitive crumble',
    usageExamples: {
      bluff_landed: '{name} served that bluff like MasterChef finale plating. Judges took one look: what the fuck is this?',
      bullshit_correct: 'Bullshit call = judge tasting the lie, {name}. Exposed on the cutting board. Four card penalty served.',
    },
  },
  {
    id: 'nandini-nailedit-gfy',
    title: 'Nailed It',
    franchise: 'nailed-it',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['gfy', 'close_call', 'heat'],
    famousMoment: 'Perfect plan in head — disaster on the table',
    quoteEnergy: 'Same confidence, half the execution',
    tone: 'wholesome fail',
    usageExamples: {
      gfy: 'Perfect plan in your head, {name}. Table result? Nailed It recreation — Go Fuck Yourself, pond miss. Same confidence, half execution.',
      close_call: 'Nailed It finale — three cards looked right, pond delivered a melted cake. Go Fuck Yourself.',
    },
  },
  {
    id: 'nandini-sugar-rush-lucky',
    title: 'Sugar Rush',
    franchise: 'sugar-rush',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['lucky', 'comeback'],
    famousMoment: 'Timed baking panic — clutch save at the buzzer',
    quoteEnergy: 'Sugar high desperation win',
    tone: 'chaotic sweet',
    usageExamples: {
      lucky: 'Go Fuck Yourself ke baad pond sympathy — Sugar Rush buzzer save, {name}. Messy but it landed.',
      comeback: '{name} was finished, then lucky draw — Sugar Rush last-second frosting. Still sub energy, still cinema.',
    },
  },
  {
    id: 'nandini-cupcake-wars-book',
    title: 'Cupcake Wars',
    franchise: 'cupcake-wars',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['book', 'steal'],
    famousMoment: 'Cupcake tower collapse — one wrong move',
    quoteEnergy: 'Decorated perfection, structural failure',
    tone: 'competitive pastry',
    usageExamples: {
      book: '{name} stacked four cards like Cupcake Wars tower — set complete before it collapsed. Kunal face: fondant cracking.',
      steal: 'Cupcake Wars snatch — {name} took one card, display still standing. Petty heist, sweet damage.',
    },
  },
  {
    id: 'nandini-spartacus-close',
    title: 'Spartacus',
    franchise: 'spartacus',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['close_call', 'heat', 'game_over'],
    famousMoment: 'Fight Rome with impossible odds',
    quoteEnergy: 'Blood and sand stubbornness',
    tone: 'epic struggle',
    usageExamples: {
      close_call: 'Teen card haath mein, {name} — Spartacus fought Rome with better odds than your pond draw.',
      heat: 'Arena has more action than this table, {name}. Go Fuck Yourself on loop, gladiators would boo.',
    },
  },
  {
    id: 'nandini-agent-sai-gfy',
    title: 'Agent Sai Srinivasa Athreya',
    franchise: 'agent-sai',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['gfy', 'bullshit_wrong', 'heat'],
    famousMoment: 'Amateur detective — wrong suspect, wrong evidence',
    quoteEnergy: 'Investigation montage, embarrassing conclusion',
    tone: 'detective comedy',
    usageExamples: {
      gfy: '{name} spent five turns investigating that hand like Agent Sai. Wrong suspect. Wrong evidence. Go Fuck Yourself.',
      bullshit_wrong: 'Agent Sai wrong case file — your bullshit call, {name}. Detective cosplay, four card penalty.',
    },
  },
  {
    id: 'nandini-hardcore-chaos',
    title: 'Hardcore Henry',
    franchise: 'hardcore-henry',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['chaos', 'steal'],
    famousMoment: 'First-person chaos — nonstop violence, no pause',
    quoteEnergy: 'POV adrenaline overdose',
    tone: 'chaotic action',
    usageExamples: {
      chaos: 'Hardcore Henry energy — {name}, table POV chaos, bartender injected violence into Go Fish.',
      steal: 'First-person snatch — {name} stole that card like Henry grabbing a weapon mid-sprint.',
    },
  },
  {
    id: 'nandini-ipman-steal',
    title: 'Ip Man',
    franchise: 'ip-man',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['steal', 'book'],
    famousMoment: 'Wing Chun speed — four hits before you blink',
    quoteEnergy: 'Calm master, devastating efficiency',
    tone: 'martial precision',
    usageExamples: {
      steal: '{name} took cards so fast Ip Man would ask you to slow the fuck down. Clean steal, dom table unchanged upstairs.',
      book: 'Ip Man finishing combo — {name} set complete, four cards, economic violence.',
    },
  },
  {
    id: 'nandini-sanju-lucky',
    title: 'Sanju',
    franchise: 'sanju',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['lucky', 'gfy', 'comeback'],
    famousMoment: 'Bad decisions montage — still survives',
    quoteEnergy: 'Mistake after mistake, reward anyway',
    tone: 'absurd survival',
    usageExamples: {
      lucky: 'Go Fuck Yourself mila, pond ne card diya — {name}, ye Sanju comeback montage hai, card game nahi.',
      gfy: 'Sanju weekend energy, {name} — galat decision, Go Fuck Yourself, phir bhi ego alive.',
      comeback: 'Everyone thought {name} was done. Lucky draw = Sanju montage music. Undeserved, iconic.',
    },
  },
  {
    id: 'nandini-ferris-lucky',
    title: "Ferris Bueller's Day Off",
    franchise: 'ferris-bueller',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['lucky', 'bluff_landed', 'roast'],
    famousMoment: 'Zero consequences — vibes only',
    quoteEnergy: 'Skipping school, winning anyway',
    tone: 'carefree scam',
    usageExamples: {
      lucky: 'Zero consequences, zero lessons, {name} — Ferris Bueller would be proud of that pond luck after Go Fuck Yourself.',
      bluff_landed: 'Ferris energy bluff — {name} lied, partner believed, no homework, full scam.',
    },
  },
  {
    id: 'nandini-gullyboy-comeback',
    title: 'Gully Boy',
    franchise: 'gully-boy',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['comeback', 'lucky', 'book'],
    famousMoment: 'Apna time aayega — underdog turns the room',
    quoteEnergy: 'Rap battle turnaround',
    tone: 'underdog triumph',
    usageExamples: {
      comeback: 'Sab soch rahe the {name} finished. Lucky draw — apna time aayega energy. Mic drop on the pond.',
      lucky: 'Go Fuck Yourself ke baad pond match — Gully Boy third act, {name}. Underground win.',
    },
  },
  {
    id: 'nandini-homebound-gfy',
    title: 'Homebound',
    franchise: 'homebound',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['gfy', 'heat'],
    famousMoment: 'Trapped tension — nowhere to escape bad choices',
    quoteEnergy: 'Claustrophobic dread',
    tone: 'indie thriller',
    usageExamples: {
      gfy: 'Homebound energy, {name} — trapped in Go Fuck Yourself loop, pond miss, no exit door.',
      heat: 'Table feels like Homebound — {name}, same room, same misses, Go Fuck Yourself on repeat.',
    },
  },
  {
    id: 'nandini-scary-chaos',
    title: 'Scary Movie',
    franchise: 'scary-movie',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['chaos', 'bluff_landed'],
    famousMoment: 'Parody chaos — rules stopped making sense',
    quoteEnergy: 'Genre parody pile-up',
    tone: 'absurd spoof',
    usageExamples: {
      chaos: 'Scary Movie rules, {name} — match stopped making sense six turns ago. Bartender agrees.',
      bluff_landed: 'Bluff so stupid it\'s Scary Movie logic — {name}, partner still believed. Go Fuck Yourself face, real cards.',
    },
  },
  {
    id: 'nandini-airplane-chaos',
    title: 'Airplane!',
    franchise: 'airplane',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['chaos', 'heat', 'bullshit'],
    famousMoment: 'Absurd escalation — nothing serious stays serious',
    quoteEnergy: 'Deadpan disaster comedy',
    tone: 'absurd',
    usageExamples: {
      chaos: 'Airplane! energy, {name} — this match quit making sense ages ago. Go Fuck Yourself is the pilot.',
      heat: 'Surely you can transfer a card, {name}. Table: no. Airplane-level absurdity.',
    },
  },
  {
    id: 'nandini-nakedgun-chaos',
    title: 'Naked Gun',
    franchise: 'naked-gun',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['chaos', 'heat', 'bullshit_correct'],
    famousMoment: 'Police procedural parody — serious tone, nonsense events',
    quoteEnergy: 'Leslie Nielsen deadpan',
    tone: 'absurd procedural',
    usageExamples: {
      chaos: 'Naked Gun territory, {name} — serious faces, nonsense table. Bartender filing a false report.',
      bullshit_correct: 'Naked Gun investigation — {name} bullshit call exposed the liar. Case closed, four cards.',
    },
  },
  {
    id: 'nandini-evaru-twist',
    title: 'Evaru',
    franchise: 'evaru',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['bullshit_correct', 'bullshit_wrong', 'bluff_landed', 'chaos'],
    famousMoment: 'Story changes every reveal',
    quoteEnergy: 'Third-act rewrite',
    tone: 'twist thriller',
    usageExamples: {
      bullshit_correct: 'Evaru reveal — {name} bullshit call, story just changed, liar caught with cards.',
      bluff_landed: 'Har turn nayi kahani, {name} — bluff landed, Evaru sequel on this table.',
      chaos: 'Every time someone understands the match, Evaru happens, {name}. Whole story changes.',
    },
  },
  {
    id: 'nandini-barbie-overconfidence',
    title: 'Barbie',
    franchise: 'barbie',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['gfy', 'close_call', 'bluff_landed'],
    famousMoment: 'Dream house confidence — reality repossesses',
    quoteEnergy: 'Pink perfection meets crash',
    tone: 'aesthetic overconfidence',
    usageExamples: {
      gfy: '{name} entered that turn like Barbie in her dream house. Go Fuck Yourself, pond miss — mortgage repossessed.',
      close_call: 'Barbie dream kitchen — three cards plated, pond said Go Fuck Yourself. Ken is crying.',
    },
  },
  {
    id: 'nandini-barbie-school-book',
    title: 'Barbie Princess Charm School',
    franchise: 'barbie-charm-school',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['book', 'roast'],
    famousMoment: 'Princess training fantasy — etiquette vs chaos',
    quoteEnergy: 'Tiara energy, messy execution',
    tone: 'fantasy comedy',
    usageExamples: {
      book: 'Charm School graduation — {name} completed the set, tiara on, Kunal still runs the kingdom.',
      roast: '{name}, questionnaire reads like Charm School confessional — princess energy, filthy homework.',
    },
  },
  {
    id: 'nandini-undisputed-steal',
    title: 'Undisputed 2',
    franchise: 'undisputed',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['steal', 'book'],
    famousMoment: 'Prison yard fight — take respect by force',
    quoteEnergy: 'Underground combat steal',
    tone: 'brutal sports',
    usageExamples: {
      steal: 'Undisputed yard snatch — {name} took that card like respect in prison. Daylight robbery.',
      book: 'Undisputed KO — four card set, {name}. Opponent still on the mat.',
    },
  },
  {
    id: 'nandini-mirchi-lucky',
    title: 'Mirchi',
    franchise: 'mirchi',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['lucky', 'comeback', 'roast'],
    famousMoment: 'Masala swagger — survives on attitude',
    quoteEnergy: 'Telugu hero spice',
    tone: 'masala flair',
    usageExamples: {
      lucky: 'Mirchi swagger — {name} got Go Fuck Yourself then pond luck. Attitude carried the scene.',
      comeback: '{name} down bad, lucky draw — Mirchi hero walk-back. Spice without logic.',
    },
  },
];

/** Kunal — questionnaire mediaFaves + structured OTT beats. */
export const KUNAL_REFERENCES = [
  {
    id: 'kunal-paatal-grind',
    title: 'Paatal Lok',
    franchise: 'paatal-lok',
    type: 'show',
    playerAffinity: 'kunal',
    triggers: ['heat', 'gfy', 'bullshit_correct'],
    famousMoment: 'Hathiram slow investigation — case open, patience brutal',
    quoteEnergy: 'Underworld paperwork grind',
    tone: 'noir patience',
    usageExamples: {
      heat: 'Paatal Lok interrogation has more transfers than this table, Kunal bhai. Go Fuck Yourself echo chamber.',
      gfy: 'Hathiram patience — Kunal bhai got Go Fuck Yourself, pond miss. Dom sloppy hour, case still open.',
    },
  },
  {
    id: 'kunal-farzi-bluff',
    title: 'Farzi',
    franchise: 'farzi',
    type: 'show',
    playerAffinity: 'kunal',
    triggers: ['bluff_landed', 'bluff_win', 'lucky'],
    famousMoment: 'Counterfeit note — confidence prints value from nothing',
    quoteEnergy: 'Sunny scam swagger',
    tone: 'con artist cool',
    usageExamples: {
      bluff_landed: 'Kunal bhai ne Go Fuck Yourself bola, cards chhupaye — Farzi Sunny clap energy. Textbook dom scam.',
      lucky: 'Farzi hustle after Go Fuck Yourself — pond matched. Counterfeit luck, real win.',
    },
  },
  {
    id: 'kunal-dhurandhar-book',
    title: 'Dhurandhar Part 1',
    franchise: 'dhurandhar-p1',
    type: 'show',
    playerAffinity: 'kunal',
    triggers: ['book', 'steal', 'game_over'],
    famousMoment: 'Mastermind audacity — owns the room',
    quoteEnergy: 'Ranveer-scale dom swagger',
    tone: 'unhinged alpha',
    usageExamples: {
      book: 'Dhurandhar planning thi, Kunal bhai — set complete, season written, Nandini never saw it.',
      game_over: 'Kunal jeet gaya — Dhurandhar finale energy. Absolute fucking cinema.',
    },
  },
  {
    id: 'kunal-dhurandhar-p2-chaos',
    title: 'Dhurandhar Part 2',
    franchise: 'dhurandhar-p2',
    type: 'show',
    playerAffinity: 'kunal',
    triggers: ['gfy', 'chaos', 'game_over'],
    famousMoment: 'Part 2 escalation — dom table gets louder',
    quoteEnergy: 'Sequel unhinged energy',
    tone: 'sequel alpha',
    usageExamples: {
      gfy: 'Dhurandhar Part 2 — Kunal bhai got Go Fuck Yourself, pond miss. Bigger swagger, same pain.',
      chaos: 'Part 2 chaos injection — Kunal bhai, table flipped mid-season.',
      game_over: 'Kunal jeet gaya — Dhurandhar Part 2 credits. Dom hour sealed.',
    },
  },
  {
    id: 'kunal-nightmanager-op',
    title: 'The Night Manager',
    franchise: 'night-manager',
    type: 'show',
    playerAffinity: 'kunal',
    triggers: ['bluff_landed', 'heat', 'comeback'],
    famousMoment: 'Quiet background operation — everyone thinks it\'s fine',
    quoteEnergy: 'Chess handler energy',
    tone: 'cool control',
    usageExamples: {
      bluff_landed: 'Night Manager op — Kunal bhai lied quiet, Nandini folded. Handler never flinched.',
      comeback: 'Table thought Kunal was cold — comeback draw. Background op just went loud.',
    },
  },
  {
    id: 'kunal-delhi-crime-lucky',
    title: 'Delhi Crime',
    franchise: 'delhi-crime',
    type: 'show',
    playerAffinity: 'kunal',
    triggers: ['lucky', 'gfy'],
    famousMoment: 'Case breaks wrong — then the one clue lands',
    quoteEnergy: 'Slow-burn cop luck',
    tone: 'procedural grit',
    usageExamples: {
      lucky: 'Delhi Crime — Go Fuck Yourself ke baad pond match, Kunal bhai. One clue, whole case turns.',
    },
  },
  {
    id: 'kunal-sacred-chaos',
    title: 'Sacred Games',
    franchise: 'sacred-games',
    type: 'show',
    playerAffinity: 'kunal',
    triggers: ['chaos', 'game_over'],
    famousMoment: 'Spiral — no peaceful night',
    quoteEnergy: 'Gaitonde chaos scream',
    tone: 'dark spiral',
    usageExamples: {
      chaos: 'Sacred Games — Kunal bhai, peaceful night cancelled. Bartender pressed chaos.',
      game_over: 'Sacred Games credits — survived spiral together, Kunal ran the op.',
    },
  },
  {
    id: 'kunal-pushpa-gfy',
    title: 'Pushpa',
    franchise: 'pushpa',
    type: 'movie',
    playerAffinity: 'kunal',
    triggers: ['gfy', 'comeback'],
    famousMoment: 'Jukega nahi saala — doesn\'t fold after miss',
    quoteEnergy: 'Swagger after whiff',
    tone: 'defiant alpha',
    usageExamples: {
      gfy: 'Pushpa energy Kunal bhai — Go Fuck Yourself, pond miss, jukega nahi. Dom still loud.',
    },
  },
  {
    id: 'kunal-bandbaaja-roast',
    title: 'Band Baaja Baaraat',
    franchise: 'band-baaja-baraat',
    type: 'movie',
    playerAffinity: 'kunal',
    triggers: ['roast', 'book'],
    famousMoment: 'Fight then flirt — hostile romance',
    quoteEnergy: 'Wedding planner chaos',
    tone: 'couple comedy',
    usageExamples: {
      roast: 'Band Baaja energy — Kunal bhai, pehle ladho phir flirt, questionnaire loaded.',
      book: 'Set complete — hostile romantic negotiation won by Kunal bhai. Nandini gets the bill.',
    },
  },
];

export const ALL_REFERENCES = [...PRIMARY_REFERENCES, ...NANDINI_REFERENCES, ...KUNAL_REFERENCES];

/** Map questionnaire mediaFaves strings → franchise ids for bonus matching. */
export const FRANCHISE_ALIASES = {
  'brooklyn nine-nine': 'brooklyn-nine-nine',
  'brooklyn 99': 'brooklyn-nine-nine',
  'b99': 'brooklyn-nine-nine',
  'modern family': 'modern-family',
  'dhoota': 'dhoota',
  'st. denis medical': 'st-denis-medical',
  'gentleman': 'gentleman',
  'masterchef india': 'masterchef-india',
  'masterchef': 'masterchef-india',
  'sugar rush': 'sugar-rush',
  'cupcake wars': 'cupcake-wars',
  'nailed it': 'nailed-it',
  'spartacus': 'spartacus',
  'agent sai': 'agent-sai',
  'agent sai srinivasa athreya': 'agent-sai',
  'hardcore henry': 'hardcore-henry',
  'ip man': 'ip-man',
  'sanju': 'sanju',
  'ferris bueller': 'ferris-bueller',
  "ferris bueller's day off": 'ferris-bueller',
  'gully boy': 'gully-boy',
  'homebound': 'homebound',
  'scary movie': 'scary-movie',
  'airplane': 'airplane',
  'airplane!': 'airplane',
  'naked gun': 'naked-gun',
  'evaru': 'evaru',
  'barbie': 'barbie',
  'barbie princess': 'barbie-charm-school',
  'charm school': 'barbie-charm-school',
  'undisputed': 'undisputed',
  'undisputed 2': 'undisputed',
  'undisputed 3': 'undisputed',
  'mirchi': 'mirchi',
  'paatal lok': 'paatal-lok',
  'farzi': 'farzi',
  'dhurandhar': 'dhurandhar-p1',
  'dhurandhar part 1': 'dhurandhar-p1',
  'dhurandhar part 2': 'dhurandhar-p2',
  'dhurandhar p1': 'dhurandhar-p1',
  'dhurandhar p2': 'dhurandhar-p2',
  'kuch kuch hota hai': 'kuch-kuch-hota-hai',
  'kkhh': 'kuch-kuch-hota-hai',
  'the night manager': 'night-manager',
  'night manager': 'night-manager',
  'delhi crime': 'delhi-crime',
  'sacred games': 'sacred-games',
  'pushpa': 'pushpa',
  'band baaja baaraat': 'band-baaja-baraat',
};
