/**
 * Contextual reference bank for Bhenchod Bartender.
 * Each entry: title, franchise, triggers, moment/character beat (not bare name-drops).
 * franchise id used for anti-repetition (no same franchise within last 5 lines).
 */

/** @typedef {'show'|'movie'} RefType */
/** @typedef {string} BartenderTrigger */

/**
 * @typedef {object} BartenderReference
 * @property {string} id
 * @property {string} title
 * @property {string} franchise
 * @property {RefType} type
 * @property {'nandini'|'kunal'|'any'} playerAffinity
 * @property {BartenderTrigger[]} triggers
 * @property {string} famousMoment
 * @property {string} quoteEnergy
 * @property {string} tone
 * @property {Partial<Record<BartenderTrigger, string>>} usageExamples
 */

/** @type {BartenderTrigger[]} */
export const BARTENDER_TRIGGERS = [
  'lucky',
  'gfy',
  'bluff_landed',
  'bluff_win',
  'bullshit_correct',
  'bullshit_wrong',
  'bullshit',
  'close_call',
  'heat',
  'chaos',
  'steal',
  'comeback',
  'book',
  'game_over',
  'roast',
  'question',
  'dare',
];

/** Nandini's watchlist — bartender should feel like he knows her taste. */
export const NANDINI_REFERENCES = [
  {
    id: 'nandini-b99-jake-bluff',
    title: 'Brooklyn Nine-Nine',
    franchise: 'brooklyn-nine-nine',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['bluff_landed', 'bluff_win', 'gfy', 'bullshit_wrong'],
    famousMoment: 'Jake Peralta overconfidence → Captain Holt deadpan disappointment',
    quoteEnergy: 'Cool cool cool cool cool — then instant regret',
    tone: 'comedic deflate',
    usageExamples: {
      bluff_landed: '{name}, you walked into that bluff with full Jake Peralta confidence. Five seconds later? Captain Holt face. Absolute fucking disaster.',
      gfy: '{name} bhai, cool cool cool cool — asked for the card, got Go Fuck Yourself, pond miss. Holt would just stare and sip water.',
      bullshit_wrong: '{name}, wrong bullshit call with Boyle-level investment. Holt energy on the table: silent judgment.',
    },
  },
  {
    id: 'nandini-b99-boyle-heat',
    title: 'Brooklyn Nine-Nine',
    franchise: 'brooklyn-nine-nine',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['heat', 'chaos'],
    famousMoment: 'Boyle way too invested in a minor situation',
    quoteEnergy: 'Overcommitted side character energy',
    tone: 'chaotic earnest',
    usageExamples: {
      heat: 'Table pe sirf Go Fuck Yourself echo ho raha hai, {name}. Boyle bhi itna invested nahi hota kisi dead case mein.',
      chaos: '{name}, chaos button = Nine-Nine precinct when paperwork catches fire. Same panic, worse cards.',
    },
  },
  {
    id: 'nandini-modfam-phil-gfy',
    title: 'Modern Family',
    franchise: 'modern-family',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['gfy', 'close_call', 'lucky'],
    famousMoment: 'Phil Dunphy optimism — everything will work out',
    quoteEnergy: 'Innocent confidence before reality hits',
    tone: 'warm then wrecked',
    usageExamples: {
      gfy: 'That ask had Phil Dunphy energy, {name}. Thought everything would work out. Then the table told you Go Fuck Yourself.',
      close_call: '{name}, teen card — Phil planning the surprise party, pond ne Go Fuck Yourself. Gloria would just yell.',
      lucky: 'Phil Dunphy luck — {name} got Go Fuck Yourself then pond sympathy. Modern Family B-plot rescue.',
    },
  },
  {
    id: 'nandini-modfam-gloria-steal',
    title: 'Modern Family',
    franchise: 'modern-family',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['steal', 'book', 'chaos'],
    famousMoment: 'Gloria chaos — loud, decisive, zero apology',
    quoteEnergy: 'Sudden domestic storm',
    tone: 'chaotic matriarch',
    usageExamples: {
      steal: '{name} ne card chura liya — Gloria entering a room energy. No warning, full volume, Kunal still owns the couch.',
      book: 'Set complete, {name} — Gloria celebration, Cam would cry, table still Kunal\'s dom hour.',
    },
  },
  {
    id: 'nandini-dhoota-warning',
    title: 'Dhoota',
    franchise: 'dhoota',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['close_call', 'gfy', 'bullshit_wrong'],
    famousMoment: 'Warnings ignored — signs everywhere, still walks into trap',
    quoteEnergy: 'Kismat messaged, you swiped away',
    tone: 'existential tease',
    usageExamples: {
      close_call: 'Warning mil gayi thi, sign mil gaya tha, {name}. Teen card, pond ne Go Fuck Yourself. Pure Dhootha energy.',
      gfy: '{name}, Dhootha twist — partner ne Go Fuck Yourself, pond miss. You had every clue, ignored all.',
    },
  },
  {
    id: 'nandini-st-denis-chaos',
    title: 'St. Denis Medical',
    franchise: 'st-denis-medical',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['chaos', 'heat'],
    famousMoment: 'Hospital chaos — competent facade, disaster behind doors',
    quoteEnergy: 'Medical sitcom panic under fluorescent lights',
    tone: 'frazzled professional',
    usageExamples: {
      chaos: 'St. Denis Medical energy, {name} — looks calm, inside pure chaos. Bartender just called code blue on this table.',
      heat: 'ER waiting room has more card transfers than this table, {name}. Go Fuck Yourself loop on repeat.',
    },
  },
  {
    id: 'nandini-gentleman-bluff',
    title: 'Gentleman',
    franchise: 'gentleman',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['bluff_landed', 'steal', 'roast'],
    famousMoment: 'Suave criminal charm — looks gentleman, moves like heist',
    quoteEnergy: 'Polite surface, dirty underneath',
    tone: 'stylish con',
    usageExamples: {
      bluff_landed: '{name} ne Go Fuck Yourself bola with Gentleman smile — cards hidden, partner folded. Suave scam.',
      steal: 'Gentleman heist — {name} slipped one card out like it was manners, not theft.',
    },
  },
  {
    id: 'nandini-masterchef-bluff',
    title: 'MasterChef India',
    franchise: 'masterchef-india',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['bluff_landed', 'bluff_win', 'bullshit_correct', 'close_call'],
    famousMoment: 'Finale plating panic — judges destroy the dish',
    quoteEnergy: 'Beautiful presentation, horrifying taste',
    tone: 'competitive crumble',
    usageExamples: {
      bluff_landed: '{name} served that bluff like MasterChef finale plating. Judges took one look: what the fuck is this?',
      bullshit_correct: 'Bullshit call = judge tasting the lie, {name}. Exposed on the cutting board. Four card penalty served.',
    },
  },
  {
    id: 'nandini-nailedit-gfy',
    title: 'Nailed It',
    franchise: 'nailed-it',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['gfy', 'close_call', 'heat'],
    famousMoment: 'Perfect plan in head — disaster on the table',
    quoteEnergy: 'Same confidence, half the execution',
    tone: 'wholesome fail',
    usageExamples: {
      gfy: 'Perfect plan in your head, {name}. Table result? Nailed It recreation — Go Fuck Yourself, pond miss. Same confidence, half execution.',
      close_call: 'Nailed It finale — three cards looked right, pond delivered a melted cake. Go Fuck Yourself.',
    },
  },
  {
    id: 'nandini-sugar-rush-lucky',
    title: 'Sugar Rush',
    franchise: 'sugar-rush',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['lucky', 'comeback'],
    famousMoment: 'Timed baking panic — clutch save at the buzzer',
    quoteEnergy: 'Sugar high desperation win',
    tone: 'chaotic sweet',
    usageExamples: {
      lucky: 'Go Fuck Yourself ke baad pond sympathy — Sugar Rush buzzer save, {name}. Messy but it landed.',
      comeback: '{name} was finished, then lucky draw — Sugar Rush last-second frosting. Still sub energy, still cinema.',
    },
  },
  {
    id: 'nandini-cupcake-wars-book',
    title: 'Cupcake Wars',
    franchise: 'cupcake-wars',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['book', 'steal'],
    famousMoment: 'Cupcake tower collapse — one wrong move',
    quoteEnergy: 'Decorated perfection, structural failure',
    tone: 'competitive pastry',
    usageExamples: {
      book: '{name} stacked four cards like Cupcake Wars tower — set complete before it collapsed. Kunal face: fondant cracking.',
      steal: 'Cupcake Wars snatch — {name} took one card, display still standing. Petty heist, sweet damage.',
    },
  },
  {
    id: 'nandini-spartacus-close',
    title: 'Spartacus',
    franchise: 'spartacus',
    type: 'show',
    playerAffinity: 'nandini',
    triggers: ['close_call', 'heat', 'game_over'],
    famousMoment: 'Fight Rome with impossible odds',
    quoteEnergy: 'Blood and sand stubbornness',
    tone: 'epic struggle',
    usageExamples: {
      close_call: 'Teen card haath mein, {name} — Spartacus fought Rome with better odds than your pond draw.',
      heat: 'Arena has more action than this table, {name}. Go Fuck Yourself on loop, gladiators would boo.',
    },
  },
  {
    id: 'nandini-agent-sai-gfy',
    title: 'Agent Sai Srinivasa Athreya',
    franchise: 'agent-sai',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['gfy', 'bullshit_wrong', 'heat'],
    famousMoment: 'Amateur detective — wrong suspect, wrong evidence',
    quoteEnergy: 'Investigation montage, embarrassing conclusion',
    tone: 'detective comedy',
    usageExamples: {
      gfy: '{name} spent five turns investigating that hand like Agent Sai. Wrong suspect. Wrong evidence. Go Fuck Yourself.',
      bullshit_wrong: 'Agent Sai wrong case file — your bullshit call, {name}. Detective cosplay, four card penalty.',
    },
  },
  {
    id: 'nandini-hardcore-chaos',
    title: 'Hardcore Henry',
    franchise: 'hardcore-henry',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['chaos', 'steal'],
    famousMoment: 'First-person chaos — nonstop violence, no pause',
    quoteEnergy: 'POV adrenaline overdose',
    tone: 'chaotic action',
    usageExamples: {
      chaos: 'Hardcore Henry energy — {name}, table POV chaos, bartender injected violence into Go Fish.',
      steal: 'First-person snatch — {name} stole that card like Henry grabbing a weapon mid-sprint.',
    },
  },
  {
    id: 'nandini-ipman-steal',
    title: 'Ip Man',
    franchise: 'ip-man',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['steal', 'book'],
    famousMoment: 'Wing Chun speed — four hits before you blink',
    quoteEnergy: 'Calm master, devastating efficiency',
    tone: 'martial precision',
    usageExamples: {
      steal: '{name} took cards so fast Ip Man would ask you to slow the fuck down. Clean steal, dom table unchanged upstairs.',
      book: 'Ip Man finishing combo — {name} set complete, four cards, economic violence.',
    },
  },
  {
    id: 'nandini-sanju-lucky',
    title: 'Sanju',
    franchise: 'sanju',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['lucky', 'gfy', 'comeback'],
    famousMoment: 'Bad decisions montage — still survives',
    quoteEnergy: 'Mistake after mistake, reward anyway',
    tone: 'absurd survival',
    usageExamples: {
      lucky: 'Go Fuck Yourself mila, pond ne card diya — {name}, ye Sanju comeback montage hai, card game nahi.',
      gfy: 'Sanju weekend energy, {name} — galat decision, Go Fuck Yourself, phir bhi ego alive.',
      comeback: 'Everyone thought {name} was done. Lucky draw = Sanju montage music. Undeserved, iconic.',
    },
  },
  {
    id: 'nandini-ferris-lucky',
    title: "Ferris Bueller's Day Off",
    franchise: 'ferris-bueller',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['lucky', 'bluff_landed', 'roast'],
    famousMoment: 'Zero consequences — vibes only',
    quoteEnergy: 'Skipping school, winning anyway',
    tone: 'carefree scam',
    usageExamples: {
      lucky: 'Zero consequences, zero lessons, {name} — Ferris Bueller would be proud of that pond luck after Go Fuck Yourself.',
      bluff_landed: 'Ferris energy bluff — {name} lied, partner believed, no homework, full scam.',
    },
  },
  {
    id: 'nandini-gullyboy-comeback',
    title: 'Gully Boy',
    franchise: 'gully-boy',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['comeback', 'lucky', 'book'],
    famousMoment: 'Apna time aayega — underdog turns the room',
    quoteEnergy: 'Rap battle turnaround',
    tone: 'underdog triumph',
    usageExamples: {
      comeback: 'Sab soch rahe the {name} finished. Lucky draw — apna time aayega energy. Mic drop on the pond.',
      lucky: 'Go Fuck Yourself ke baad pond match — Gully Boy third act, {name}. Underground win.',
    },
  },
  {
    id: 'nandini-homebound-gfy',
    title: 'Homebound',
    franchise: 'homebound',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['gfy', 'heat'],
    famousMoment: 'Trapped tension — nowhere to escape bad choices',
    quoteEnergy: 'Claustrophobic dread',
    tone: 'indie thriller',
    usageExamples: {
      gfy: 'Homebound energy, {name} — trapped in Go Fuck Yourself loop, pond miss, no exit door.',
      heat: 'Table feels like Homebound — {name}, same room, same misses, Go Fuck Yourself on repeat.',
    },
  },
  {
    id: 'nandini-scary-chaos',
    title: 'Scary Movie',
    franchise: 'scary-movie',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['chaos', 'bluff_landed'],
    famousMoment: 'Parody chaos — rules stopped making sense',
    quoteEnergy: 'Genre parody pile-up',
    tone: 'absurd spoof',
    usageExamples: {
      chaos: 'Scary Movie rules, {name} — match stopped making sense six turns ago. Bartender agrees.',
      bluff_landed: 'Bluff so stupid it\'s Scary Movie logic — {name}, partner still believed. Go Fuck Yourself face, real cards.',
    },
  },
  {
    id: 'nandini-airplane-chaos',
    title: 'Airplane!',
    franchise: 'airplane',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['chaos', 'heat', 'bullshit'],
    famousMoment: 'Absurd escalation — nothing serious stays serious',
    quoteEnergy: 'Deadpan disaster comedy',
    tone: 'absurd',
    usageExamples: {
      chaos: 'Airplane! energy, {name} — this match quit making sense ages ago. Go Fuck Yourself is the pilot.',
      heat: 'Surely you can transfer a card, {name}. Table: no. Airplane-level absurdity.',
    },
  },
  {
    id: 'nandini-nakedgun-chaos',
    title: 'Naked Gun',
    franchise: 'naked-gun',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['chaos', 'heat', 'bullshit_correct'],
    famousMoment: 'Police procedural parody — serious tone, nonsense events',
    quoteEnergy: 'Leslie Nielsen deadpan',
    tone: 'absurd procedural',
    usageExamples: {
      chaos: 'Naked Gun territory, {name} — serious faces, nonsense table. Bartender filing a false report.',
      bullshit_correct: 'Naked Gun investigation — {name} bullshit call exposed the liar. Case closed, four cards.',
    },
  },
  {
    id: 'nandini-evaru-twist',
    title: 'Evaru',
    franchise: 'evaru',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['bullshit_correct', 'bullshit_wrong', 'bluff_landed', 'chaos'],
    famousMoment: 'Story changes every reveal',
    quoteEnergy: 'Third-act rewrite',
    tone: 'twist thriller',
    usageExamples: {
      bullshit_correct: 'Evaru reveal — {name} bullshit call, story just changed, liar caught with cards.',
      bluff_landed: 'Har turn nayi kahani, {name} — bluff landed, Evaru sequel on this table.',
      chaos: 'Every time someone understands the match, Evaru happens, {name}. Whole story changes.',
    },
  },
  {
    id: 'nandini-barbie-overconfidence',
    title: 'Barbie',
    franchise: 'barbie',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['gfy', 'close_call', 'bluff_landed'],
    famousMoment: 'Dream house confidence — reality repossesses',
    quoteEnergy: 'Pink perfection meets crash',
    tone: 'aesthetic overconfidence',
    usageExamples: {
      gfy: '{name} entered that turn like Barbie in her dream house. Go Fuck Yourself, pond miss — mortgage repossessed.',
      close_call: 'Barbie dream kitchen — three cards plated, pond said Go Fuck Yourself. Ken is crying.',
    },
  },
  {
    id: 'nandini-barbie-school-book',
    title: 'Barbie Princess Charm School',
    franchise: 'barbie-charm-school',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['book', 'roast'],
    famousMoment: 'Princess training fantasy — etiquette vs chaos',
    quoteEnergy: 'Tiara energy, messy execution',
    tone: 'fantasy comedy',
    usageExamples: {
      book: 'Charm School graduation — {name} completed the set, tiara on, Kunal still runs the kingdom.',
      roast: '{name}, questionnaire reads like Charm School confessional — princess energy, filthy homework.',
    },
  },
  {
    id: 'nandini-undisputed-steal',
    title: 'Undisputed 2',
    franchise: 'undisputed',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['steal', 'book'],
    famousMoment: 'Prison yard fight — take respect by force',
    quoteEnergy: 'Underground combat steal',
    tone: 'brutal sports',
    usageExamples: {
      steal: 'Undisputed yard snatch — {name} took that card like respect in prison. Daylight robbery.',
      book: 'Undisputed KO — four card set, {name}. Opponent still on the mat.',
    },
  },
  {
    id: 'nandini-mirchi-lucky',
    title: 'Mirchi',
    franchise: 'mirchi',
    type: 'movie',
    playerAffinity: 'nandini',
    triggers: ['lucky', 'comeback', 'roast'],
    famousMoment: 'Masala swagger — survives on attitude',
    quoteEnergy: 'Telugu hero spice',
    tone: 'masala flair',
    usageExamples: {
      lucky: 'Mirchi swagger — {name} got Go Fuck Yourself then pond luck. Attitude carried the scene.',
      comeback: '{name} down bad, lucky draw — Mirchi hero walk-back. Spice without logic.',
    },
  },
];

/** Kunal — questionnaire mediaFaves + structured OTT beats (avoid bare Mirzapur spam). */
export const KUNAL_REFERENCES = [
  {
    id: 'kunal-paatal-grind',
    title: 'Paatal Lok',
    franchise: 'paatal-lok',
    type: 'show',
    playerAffinity: 'kunal',
    triggers: ['heat', 'gfy', 'bullshit_correct'],
    famousMoment: 'Hathiram slow investigation — case open, patience brutal',
    quoteEnergy: 'Underworld paperwork grind',
    tone: 'noir patience',
    usageExamples: {
      heat: 'Paatal Lok interrogation has more transfers than this table, Kunal bhai. Go Fuck Yourself echo chamber.',
      gfy: 'Hathiram patience — Kunal bhai got Go Fuck Yourself, pond miss. Dom sloppy hour, case still open.',
    },
  },
  {
    id: 'kunal-farzi-bluff',
    title: 'Farzi',
    franchise: 'farzi',
    type: 'show',
    playerAffinity: 'kunal',
    triggers: ['bluff_landed', 'bluff_win', 'lucky'],
    famousMoment: 'Counterfeit note — confidence prints value from nothing',
    quoteEnergy: 'Sunny scam swagger',
    tone: 'con artist cool',
    usageExamples: {
      bluff_landed: 'Kunal bhai ne Go Fuck Yourself bola, cards chhupaye — Farzi Sunny clap energy. Textbook dom scam.',
      lucky: 'Farzi hustle after Go Fuck Yourself — pond matched. Counterfeit luck, real win.',
    },
  },
  {
    id: 'kunal-dhurandhar-book',
    title: 'Dhurandhar',
    franchise: 'dhurandhar',
    type: 'show',
    playerAffinity: 'kunal',
    triggers: ['book', 'steal', 'game_over'],
    famousMoment: 'Mastermind audacity — owns the room',
    quoteEnergy: 'Ranveer-scale dom swagger',
    tone: 'unhinged alpha',
    usageExamples: {
      book: 'Dhurandhar planning thi, Kunal bhai — set complete, season written, Nandini never saw it.',
      game_over: 'Kunal jeet gaya — Dhurandhar finale energy. Absolute fucking cinema.',
    },
  },
  {
    id: 'kunal-mirzapur-throne',
    title: 'Mirzapur',
    franchise: 'mirzapur',
    type: 'show',
    playerAffinity: 'kunal',
    triggers: ['book', 'steal', 'game_over'],
    famousMoment: 'Who sits the chair runs the turf',
    quoteEnergy: 'Mukhtar table hierarchy',
    tone: 'power throne',
    usageExamples: {
      steal: 'Mirzapur loot — Kunal bhai seedha haath daal ke card. Daylight robbery on his turf.',
      book: 'Jo kursi pe baitha hai wohi raja — Kunal bhai, four cards, throne secure.',
    },
  },
  {
    id: 'kunal-nightmanager-op',
    title: 'The Night Manager',
    franchise: 'night-manager',
    type: 'show',
    playerAffinity: 'kunal',
    triggers: ['bluff_landed', 'heat', 'comeback'],
    famousMoment: 'Quiet background operation — everyone thinks it\'s fine',
    quoteEnergy: 'Chess handler energy',
    tone: 'cool control',
    usageExamples: {
      bluff_landed: 'Night Manager op — Kunal bhai lied quiet, Nandini folded. Handler never flinched.',
      comeback: 'Table thought Kunal was cold — comeback draw. Background op just went loud.',
    },
  },
  {
    id: 'kunal-delhi-crime-lucky',
    title: 'Delhi Crime',
    franchise: 'delhi-crime',
    type: 'show',
    playerAffinity: 'kunal',
    triggers: ['lucky', 'gfy'],
    famousMoment: 'Case breaks wrong — then the one clue lands',
    quoteEnergy: 'Slow-burn cop luck',
    tone: 'procedural grit',
    usageExamples: {
      lucky: 'Delhi Crime — Go Fuck Yourself ke baad pond match, Kunal bhai. One clue, whole case turns.',
    },
  },
  {
    id: 'kunal-sacred-chaos',
    title: 'Sacred Games',
    franchise: 'sacred-games',
    type: 'show',
    playerAffinity: 'kunal',
    triggers: ['chaos', 'game_over'],
    famousMoment: 'Spiral — no peaceful night',
    quoteEnergy: 'Gaitonde chaos scream',
    tone: 'dark spiral',
    usageExamples: {
      chaos: 'Sacred Games — Kunal bhai, peaceful night cancelled. Bartender pressed chaos.',
      game_over: 'Sacred Games credits — survived spiral together, Kunal ran the op.',
    },
  },
  {
    id: 'kunal-pushpa-gfy',
    title: 'Pushpa',
    franchise: 'pushpa',
    type: 'movie',
    playerAffinity: 'kunal',
    triggers: ['gfy', 'comeback'],
    famousMoment: 'Jukega nahi saala — doesn\'t fold after miss',
    quoteEnergy: 'Swagger after whiff',
    tone: 'defiant alpha',
    usageExamples: {
      gfy: 'Pushpa energy Kunal bhai — Go Fuck Yourself, pond miss, jukega nahi. Dom still loud.',
    },
  },
  {
    id: 'kunal-bandbaaja-roast',
    title: 'Band Baaja Baaraat',
    franchise: 'band-baaja-baraat',
    type: 'movie',
    playerAffinity: 'kunal',
    triggers: ['roast', 'book'],
    famousMoment: 'Fight then flirt — hostile romance',
    quoteEnergy: 'Wedding planner chaos',
    tone: 'couple comedy',
    usageExamples: {
      roast: 'Band Baaja energy — Kunal bhai, pehle ladho phir flirt, questionnaire loaded.',
      book: 'Set complete — hostile romantic negotiation won by Kunal bhai. Nandini gets the bill.',
    },
  },
];

export const ALL_REFERENCES = [...NANDINI_REFERENCES, ...KUNAL_REFERENCES];

/** Map questionnaire mediaFaves strings → franchise ids for bonus matching. */
export const FRANCHISE_ALIASES = {
  'brooklyn nine-nine': 'brooklyn-nine-nine',
  'brooklyn 99': 'brooklyn-nine-nine',
  'b99': 'brooklyn-nine-nine',
  'modern family': 'modern-family',
  'dhoota': 'dhoota',
  'st. denis medical': 'st-denis-medical',
  'gentleman': 'gentleman',
  'masterchef india': 'masterchef-india',
  'masterchef': 'masterchef-india',
  'sugar rush': 'sugar-rush',
  'cupcake wars': 'cupcake-wars',
  'nailed it': 'nailed-it',
  'spartacus': 'spartacus',
  'agent sai': 'agent-sai',
  'agent sai srinivasa athreya': 'agent-sai',
  'hardcore henry': 'hardcore-henry',
  'ip man': 'ip-man',
  'sanju': 'sanju',
  'ferris bueller': 'ferris-bueller',
  "ferris bueller's day off": 'ferris-bueller',
  'gully boy': 'gully-boy',
  'homebound': 'homebound',
  'scary movie': 'scary-movie',
  'airplane': 'airplane',
  'airplane!': 'airplane',
  'naked gun': 'naked-gun',
  'evaru': 'evaru',
  'barbie': 'barbie',
  'barbie princess': 'barbie-charm-school',
  'charm school': 'barbie-charm-school',
  'undisputed': 'undisputed',
  'undisputed 2': 'undisputed',
  'undisputed 3': 'undisputed',
  'mirchi': 'mirchi',
  'paatal lok': 'paatal-lok',
  'farzi': 'farzi',
  'dhurandhar': 'dhurandhar',
  'mirzapur': 'mirzapur',
  'the night manager': 'night-manager',
  'night manager': 'night-manager',
  'delhi crime': 'delhi-crime',
  'sacred games': 'sacred-games',
  'pushpa': 'pushpa',
  'band baaja baaraat': 'band-baaja-baraat',
};
